name: Demonstrate Dependency Caching

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      # This step attempts to restore a cache with the specific key
      - name: Cache dependencies
        id: cache-step # An ID is needed to reference the output of this step
        uses: actions/cache@v4
        with:
          # Define the file/folder to cache
          path: dummy_dependencies
          # The exact key required by the prompt
          key: cache-fa01e5b

      # This step runs ONLY if the cache was not found in the previous step
      - name: Create dependency file if cache missed
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: |
          echo "Cache not found. Priming cache by creating a dummy file."
          echo "This content was generated on the first run." > dummy_dependencies

      # --- THIS IS THE REQUIRED VERIFICATION STEP ---
      # It has the correct name and echoes the cache hit/miss status.
      # The 'run' command is now in a literal block to avoid syntax errors.
      - name: prime-cache-fa01e5b
        run: |
          echo "The cache hit status was: ${{ steps.cache-step.outputs.cache-hit }}"

      # This is an optional step to prove the cached file exists and has content
      - name: Verify content of cached file
        run: |
          echo "--- Verifying file content ---"
          cat dummy_dependencies
          echo "----------------------------"